### ISSUE TITLE
Visual route editor

### ISSUE THREAD

**Issue by Gabbiano83BG** [Map-A-Droid/MAD#1057]
Hi,
adding a route editor on the madmin panel could be a real improvement.
I mean, currently changing a stop point on a device route require manually inserting coordinates, a future improvement should be permit editing route points as from already happen on area.
Optimizing routes is very time consuming and I think that a area-like editor will dramatically improve the speed and the yield of the devices.

**Comment by MrJul** [comment]
I had a go at this and it works fine if you want to try: https://github.com/MrJul/MAD/tree/route-editor

I didn't PR that yet because there's a problem: routes are grabbed from the route manager (memory) but are saved directly to the database. This discrepancy means that once a route is edited, if the map is refreshed, the changes are visually gone until new settings are applied.

It's logical (areas/routes on the map don't really change until you apply settings), but it makes for a pretty bad user experience when editing. I'm not sure what the best way to solve this: having two kinds of routes on the map (unapplied and applied)? That would also be quite confusing...

**Comment by Gabbiano83BG** [comment]
Hi, It works like a charm! Thanks, this improve really time spent in route optimization

**Comment by dkmur** [comment]
great stuff !!!

**Comment by ChaosEmpire** [comment]
please PR this

mad itself needs a rework, after switching all to the database, dynamic apply of settings is a step missing, particular reload of settings, not a full reload at all

as this wont come soon, just make a hint, edited route, you wont see...until apply settings

the plus for all is bigger than the issue to tell someone that he needs an apply in discord

**Comment by gabbiano83** [comment]
Hi, 
is it possible to integrate this code on master branch?

**Comment by MrJul** [comment]
Opened PR #1109 (read to know how the "route visually lost on refresh" problem was handled).
