### ISSUE TITLE
Improve resource consumtion

### ISSUE THREAD

**Issue by Fireobirdy** [Map-A-Droid/MAD#1083]
Restarting madmin has a significant impact on the resources needed. It can be done manualy from time to time, of course, but it shouldn't. I won't call it bug or feature request. Maybe enhancement in the long run.
![madmin_perf](https://user-images.githubusercontent.com/24521649/103343977-94aad580-4a8d-11eb-8b39-0834870f819b.PNG)

**Comment by reedy** [comment]
Unused memory is wasted memory

**Comment by sn0opy** [comment]
I would consider this, if this was an actual memory leak resulting in a memory consumption growth over time. But it stops growing at a certain time because MAD simply holds several things in memory for faster access. IV lists, enounter IDs for mons to to be encounterd by PD and so one are just some examples of things almost always staying in memory.
