### ISSUE TITLE
missing and unused settings

### ISSUE THREAD

**Issue by temp666** [Map-A-Droid/MAD#449]
I updated my config.ini to the latest version with the latest config.ini.example and found that the OCR was pretty slow and the Quest scan was at about 100 pieces.
After searching I found out that the setting _--ocr_thread_count_ is no longer in the config, but still in use. I also noticed that in walkerArgs.py many config are no longer used.
Are there any more settings that are still in use but have been removed from config.ini?

**Comment by sn0opy** [comment]
It has just been removed from the sample config.ini. that's nothing to worry about. Every parameter in the walkerArgs.py can either the used as a parameter or as config.ini setting

**Comment by temp666** [comment]
Thanks.
Doesn't it make sense to keep them in sync then?  Not that sometime removing settings with the statement was not in the config/supported.

**Comment by sn0opy** [comment]
Ususally the config.ini is only updated to give people helpful or even needed option right at a glance since most people don't even know, that MAD can be started with `--help` to get all the possible commands.

Things being added to the sample config.ini are mostly disabled or have default values anyway. No need to keep it updated.

**Comment by temp666** [comment]
ok, thanks for the clarification.
