### ISSUE TITLE
Mon Stats show wrong values

### ISSUE THREAD

**Issue by ChaosEmpire** [Map-A-Droid/MAD#472]
After removing one mon mitm device, but activating prioq at same time, Mon stats starts showing huge more sum spawns per hour

sn0opy script shows ~ 25% percent less pokemon than before, which is ok, as 1 of 4 devices is gone

I assume that hopping to a prioq point, counts the new spawned pokemon, as expected, but also double counts all already counted pokemon which are currently active in device view range,

as an external shiny script also sometmes reports the same shiny several times (every round of device), it seems, that even iv scanned pokemon get encountered another time, if there are non others (and surely counted again cause of that)

**Comment by sn0opy** [comment]
Well, you external script is broken because you didn't consider the way the raw stats table works. So it's completely fine that it contains duplicates, but the final calculations just has to consider this. And yes, if you run mon_mitm with an IV lists, those mons will be re-encountered. That's normal and takes a shitton of useless effort to change that.

Regarding stats in general: probably requires another look into it. not sure, how they're actually accumulated.

**Comment by Expl0dingBanana** [comment]
Is this still an issue after splitting the tables?

**Comment by Expl0dingBanana** [comment]
Closed due to inactivity
