### ISSUE TITLE
"only route" calc crashes

### ISSUE THREAD

**Issue by Axiangel** [Map-A-Droid/MAD#524]
Not much to add, "python3 start.py -or" runs for a few minutes, but when it is about to start the calc in quickmode it throws this EOFerror

Related to #523 ?
https://pasteyour.cf/ayimuxigit.sql

**Comment by pki0** [comment]
How much memory does your server have?
I only get this error if I use `optimized` for larges routes with stops. After a while my server is out of memory and then it returns the error. Because of that I'm calculating only single routes (one route per -or)

You can look at your memory using e.g. `htop` after starting with -or.
