### ISSUE TITLE
quest_pub authentication issue

### ISSUE THREAD

**Issue by boby360** [Map-A-Droid/MAD#557]
When "quests_public" is enabled in the config and navigate to /quests_pub, a authentication window appears after trying to select something from the drop down menu.

Tested on multiple installs that are up to date.

**Comment by crhbetz** [comment]
I think the issue lies here, from https://github.com/Map-A-Droid/MAD/commit/f0f039e48019f59f7db0faed54bfaa277b5dadef: https://github.com/Map-A-Droid/MAD/blob/8d6efa36a62aeac9c418254d33d087be87ba8962/madmin/templates/quests.html#L86

Something like this fixes weird behaviours for me:
```diff --git a/madmin/templates/quests.html b/madmin/templates/quests.html
--- a/madmin/templates/quests.html
+++ b/madmin/templates/quests.html
@@ -83,7 +83,11 @@
         });
         $('#area').change(function() {
             area = $(this).find("option:selected").attr('value');
+            {% if pub %}
+            window.location.href = window.location.href.split('?')[0] + '?fence=' + area
+            {% else %}
             window.location.href = '{{ url_for('quest') }}?fence=' + area
+            {% endif %}
         });
     });
```
No idea if that is good code though. Someone with more knowledge should take a look.
If you just use `window.location.href = '{{ url_for('quest_pub') }}?fence=' + area` - difference being `quest_pub` instead of `quest`, you'll have issues with reverse proxying.

**Comment by boby360** [comment]
Above sadly didn't work. However DrMurx in Discord mentioned that they would make a patch.
