### ISSUE TITLE
PrioQ workers will not connect after commit "0c0f774 prioQ fixes for mon_mitm, little improvements," was introduced.

### ISSUE THREAD

**Issue by BadWolf0081** [Map-A-Droid/MAD#673]
Any pull after "0c0f774 prioQ fixes for mon_mitm, little improvements," results in my larger PrioQ Mon_mitm area not allowing workers to connect.  it will connect 1 for 1 location then disconnect it, status does not update on the devices even though they are sending GMO to the console.

git reset --hard fac3719  Instantly resolves this issue.

at least 3 other users have reported the same behavior on discord.

**Comment by PurseChicken** [comment]
I also have this issue and would be happy to provide anything that helps identify the root cause.

All of the Pokemon scanning devices have this problem. Quests and Raid scanning do not. MADevice keeps reporting many devices that have "no data" because of this. As well as other logic for monitoring device health.

**Comment by bbdoc** [comment]
I confirm I see the same issue. On raid scan, devices do seem to connect but very slowly. I took a 5 minutes log with `0c0f774` and only had 32 devices connected. Same log rolling back before this commit and all devices (75) were successfully connected in less than 3 minutes. Couldn't find any specific error in log except a lot of no mitm data received.

**Comment by crhbetz** [comment]
For reference, you're saying 0c0f7745aa0d77057d8e35c3d0d9a9fcfe17f005 (#610) is where these problems start.

I'm confused as to how these problems could be related to the changes I've made - I haven't modified any code relating to device connections and don't see the issue on my installation. I really don't know this part of the code at all.
Reading the following function, I'd say injection status is determined purely by receiving any sort of proto data from PogoDroid, regardless of scanner type / mode:
https://github.com/Map-A-Droid/MAD/blob/7e126e7411ede18d5b9839e7b99330b4e62594a1/mitm_receiver/MITMReceiver.py#L134-L144

What I would do to start digging would be:

1. check `logcat | grep Proto` on affected devices for any anomalies / hints
2. check -vv log for `Receiving proto from` log line for affected devices

You can provide this info to me via Discord if you have privacy concerns posting it here.

Maybe someone who is more knowledgeable with the `mitm_receiver` part of the code might have better ideas.

**Comment by BadWolf0081** [comment]
I sent you -vvv logs of it working on the commit before this, and of what it does with the current commits.  I do not believe the issue is directly with connections since quest scans work fine as do other types of scans.  Only PrioQ Mon_mitm large areas seems to be effected.  I believe it's something in the route building or assigning process that is bugged.

if one of the others could do the logcat info that would be great since I haven't got a clue where to start about doing that. especially not sure why we need it since just reverting to the pull before yours fixes this like a miracle... 

can we not just pull that little bit of code you changed that should effect things and see if it fixes it on the latest pull?

**Comment by crhbetz** [comment]
Ok, judging from the logs I think the clustering process blows up because of too many events. We get the output from this:
https://github.com/Map-A-Droid/MAD/blob/042707ed4c4dce8a6955aabe2273ab2e16ee1138/route/RouteManagerBase.py#L384
but none of the log output after that point. It makes sense because the cost of recursing through an increasing number of locations probably increases exponentially. That would be why it works on smaller areas and blows up on larger ones.
I'll have to think about how to get this under control ...

**Comment by bbdoc** [comment]
In the meantime, is there any way you could deactivate this so we can pull latest master and check that it works fine (which would confirm this is indeed the issue) ?

**Comment by crhbetz** [comment]
Maybe try `git revert 0c0f7745aa0d77057d8e35c3d0d9a9fcfe17f005` locally. Should create a commit to undo all changes by the commit given and leave the rest alone.
No time to dig deeper or try this myself right now, sorry.

**Comment by bbdoc** [comment]
ok will give it a try and let you know. Thanks

**Comment by BadWolf0081** [comment]
I get an error that it creates conflicts, I didn't try running it I just went back to the working commit as I need to continue scanning.

**Comment by bbdoc** [comment]
Indeed, conflicts in `route/RouteManagerBase.py` and from what I could see at first glance, this goes over a large section of code, so not an easy conflict to resolve :-/

**Comment by bbdoc** [comment]
@BadWolf0081 

From what I understand the issue is in this part of the code :

```
                if self.mode == "mon_mitm":
                    new_queue = self._filter_priority_queue_internal(new_queue)
                    logger.info("Merging existing Q of {} events with {} "
                        "clustered new events", len(self._prio_queue), len(new_queue))
                    merged = set(new_queue + self._prio_queue)
                    merged = list(merged)
                    logger.info("Merging resulted in queue with {} entries", len(merged))
                    merged = self._filter_priority_queue_internal(merged, cluster=False)
                else:
```

So if you just pull latest master and change `if self.mode == "mon_mitm":` to anything that doesn't exist, e.g. : `if self.mode == "mon_mitm_test":` it will never get into the if, and will fall back on the else, meaning previous behaviour.

Don't have time to test it right now as I need to leave but will test it this evening unless you want to give it a try ;-)

**Comment by BadWolf0081** [comment]
This is way beyond my abilities so I'm forced to wait for someone to confirm they have fixed it before I pull the latest again.  If a dev could try and make this change and give us a PR that would be awesome!

**Comment by crhbetz** [comment]
Guys, I'm pretty sure we know what the issue is and I'm talking to cec about how to best mitigate it right now. This will be fixed. Don't panic :-)
Stay at https://github.com/Map-A-Droid/MAD/commit/fac3719f6e4099c2dcb666c394dde896a69311ab for a couple more hours if you're affected, or break up your huge areas into smaller ones.

**Comment by BadWolf0081** [comment]
It would appear this issue, or one very similar to it was re-introduced yesterday.  Reverting to 77113e5 works, however the latest master pull stops my prioq workers from connecting again.  I will not be able to provide logs until later tonight.

**Comment by BadWolf0081** [comment]
This has now been resolved and working very well for a few days.  Closing the Issue.
