### ISSUE TITLE
Gyms and spawns are not clickable on mobile

### ISSUE THREAD

**Issue by sn0opy** [Map-A-Droid/MAD#737]
Gyms and spawns are not currently clickable on mobile (tested with 2 phones, maps centers on gym/spawn position but does not present gym/spawn details data window)

_Originally posted by @ColdShadow80 in https://github.com/Map-A-Droid/MAD/issues/682#issuecomment-582829386_

**Comment by sn0opy** [comment]
I can kinda reproduce this. The map centers but if you click the same gym again, it will open the popup. Sometimes it even works on first try when there's enough space for the popup

**Comment by ColdShadow80** [comment]
I have revisited the page and since noticed 2 things. 
1. Landscape mode allows clicking on most gyms, but not all. This seems consistent with your previous comment. 
2. Thumbnail increased by a lot. Used to have gym image inside the circle, now I see 1/4center image of the gym. Probably related to the same bug.
