### ISSUE TITLE
"Raw POST" problems in PD 1.7.0.2

### ISSUE THREAD

**Issue by ayrshire** [Map-A-Droid/MAD#969]
I'm using MAD, ATV with PD posting raw data to RDM.
I meet 2 problems and I have one update:

The problems:
1. In MAD:
If a "mon_mitm" device starts from boot, it could go around 10 positions. MAD will not able to receive further GMO data. It will go to the timeout then reboot flow.

2. In RDM:
I found the raw data from PD is the same.
It will send a lot requests to RDM. However, their contents are the same.
If the device reboots, PD will send a different one. However, the following contents will be the same.

Software versions on my devices:
[RGC 1.14.0 | PD 1.7.0.2 | PoGo 0.185.0 | ROM 1.3.3]

The configurations are fine before updating.

The latest update:
Once I disable the "raw post" of Pogodroid, MAD will be fine.
However, our service relied on PD to post raw data to RDM
Could somebody involved in PD can help?

**Comment by kamieniarz** [comment]
I think that's what affected all of my 47 devices during questing this night. I rebooted all devices and restarted mad few hours ago so everything works now. I haven't checked logs but this kind of strange behaviour happend for the first time to me. Next time I'll grab logs cause I treated that as another random MAD issue 🤷

**Comment by sn0opy** [comment]
As discussed on Discord, there's no indication of an actual issue here. With 0.185.0 some protos are being requested way more frequently. Especially things like 5017 is appearing every few seconds with the exact same response. That proto isn't evne used for mapping anyway. 

If you encounter any issues on the RDM's end, put a proxy inbetween to filter out useless protos. Checkout https://github.com/SkOODaT/PDToRDM

We're going to push another update to PD to filter out empty inventory deltas as they're appearing more frequently as well.
